a1 = input("enter the fruit num1\n")
a2 = input("enter the fruit num2\n")
a3 = input("enter the fruit num3\n")
a4 = input("enter the fruit num4\n")
a5 = input("enter the fruit num5\n")
a6 = input("enter the fruit num6\n")
a7 = input("enter the fruit num7\n")
a8 = input("enter the fruit num8\n")
a9 = input("enter the fruit num9\n")
a10 = input("enter the fruit num10\n")
a12 = input("enter the fruit num11\n")
a13 = input("enter the fruit num12\n")
a14 = input("enter the fruit num13\n")
a15 = input("enter the fruit num14\n")
list = [a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a12,a13,a14,a15]
print(list)
